CREATE OR REPLACE EDITIONABLE PACKAGE "YODA"."TEST_INOUT_OUT_AS_FN_PARAM" AS
    type  typ IS RECORD  (a NUMBER, b VARCHAR2(10));
    TYPE dom1 IS VARRAY(300) OF INTEGER;
END test_inout_out_as_fn_param;
/
;
