CREATE OR REPLACE EDITIONABLE TRIGGER "YODA"."PLAYER_ID_TRG" 
  BEFORE INSERT ON player
  FOR EACH ROW
DECLARE
BEGIN
  IF( :new.id IS NULL )
  THEN
    :new.id := player_seq.nextval;
  END IF;
END;

/
ALTER TRIGGER "YODA"."PLAYER_ID_TRG" ENABLE;
