CREATE OR REPLACE EDITIONABLE TRIGGER "YODA"."SPORT_TEAM_ID_TRG" 
  BEFORE INSERT ON sport_team
  FOR EACH ROW
DECLARE
BEGIN
  IF( :new.id IS NULL )
  THEN
    :new.id := sport_team_seq.nextval;
  END IF;
END;
/
ALTER TRIGGER "YODA"."SPORT_TEAM_ID_TRG" ENABLE;
