CREATE OR REPLACE EDITIONABLE TRIGGER "YODA"."SPORTING_EVENT_ID_TRG" 
  BEFORE INSERT ON sporting_event
  FOR EACH ROW
DECLARE
BEGIN
  IF( :new.id IS NULL )
  THEN
    :new.id := sporting_event_seq.nextval;
  END IF;
END;





ALTER TRIGGER "YODA"."SPORTING_EVENT_ID_TRG" ENABLE;

ALTER TRIGGER "YODA"."SPORTING_EVENT_ID_TRG" 
  COMPILE 
    PLSQL_OPTIMIZE_LEVEL=  2
    PLSQL_CODE_TYPE=  INTERPRETED    PLSCOPE_SETTINGS=  'IDENTIFIERS:NONE'
;
CREATE EDITIONABLE TRIGGER "YODA"."TRG_EMPAUDIT" 
  BEFORE INSERT
  on  employee_audits
  for each row
begin
   SELECT employee_audits_id.NEXTVAL INTO :new.id FROM DUAL;
END;






ALTER TRIGGER "YODA"."TRG_EMPAUDIT" ENABLE;

ALTER TRIGGER "YODA"."TRG_EMPAUDIT" 
  COMPILE 
    PLSQL_OPTIMIZE_LEVEL=  2
    PLSQL_CODE_TYPE=  INTERPRETED    PLSCOPE_SETTINGS=  'IDENTIFIERS:ALL'
;
CREATE EDITIONABLE TRIGGER "YODA"."EMP_TRGIGGER" 
  BEFORE UPDATE
  ON employees
  FOR EACH ROW
  BEGIN
  IF :new.last_name <> :old.last_name THEN
		 INSERT INTO employee_audits(employee_id,last_name,changed_on)
		 VALUES(:old.id,:old.last_name,SYSDATE);
	END IF;
  END; 






ALTER TRIGGER "YODA"."EMP_TRGIGGER" ENABLE;

ALTER TRIGGER "YODA"."EMP_TRGIGGER" 
  COMPILE 
    PLSQL_OPTIMIZE_LEVEL=  2
    PLSQL_CODE_TYPE=  INTERPRETED    PLSCOPE_SETTINGS=  'IDENTIFIERS:ALL'
;
CREATE EDITIONABLE TRIGGER "YODA"."TRG_EMP" 
  BEFORE INSERT
  on  employees
  for each row
begin
   SELECT employees_id_seq.NEXTVAL INTO :new.id FROM DUAL;
END;






ALTER TRIGGER "YODA"."TRG_EMP" ENABLE;

ALTER TRIGGER "YODA"."TRG_EMP" 
  COMPILE 
    PLSQL_OPTIMIZE_LEVEL=  2
    PLSQL_CODE_TYPE=  INTERPRETED    PLSCOPE_SETTINGS=  'IDENTIFIERS:ALL'
;
CREATE EDITIONABLE TRIGGER "YODA"."SPORT_TEAM_ID_TRG" 
  BEFORE INSERT ON sport_team
  FOR EACH ROW
DECLARE
BEGIN
  IF( :new.id IS NULL )
  THEN
    :new.id := sport_team_seq.nextval;
  END IF;
END;





ALTER TRIGGER "YODA"."SPORT_TEAM_ID_TRG" ENABLE;

ALTER TRIGGER "YODA"."SPORT_TEAM_ID_TRG" 
  COMPILE 
    PLSQL_OPTIMIZE_LEVEL=  2
    PLSQL_CODE_TYPE=  INTERPRETED    PLSCOPE_SETTINGS=  'IDENTIFIERS:NONE';
/
ALTER TRIGGER "YODA"."SPORTING_EVENT_ID_TRG" ENABLE;
