-- DMAP_OBJECT_GEN_TAG : TYPE : SERVER NAME : APSQT_LINK
SET search_path = demo,oracle,dmap_extension,public;/* DMAP CONVERTED STATEMENT START */CREATE EXTENSION IF NOT EXISTS  dblink;
CREATE EXTENSION IF NOT EXISTS oracle_fdw;
CREATE SERVER APSQT_LINK  FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host '192.168.1.12', port '1521');/* DMAP CONVERTED STATEMENT END */
