-- DMAP_OBJECT_GEN_TAG : TYPE : SERVER NAME : DBLINK_2_SERVERS
SET search_path = demo,oracle,dmap_extension,public;/* DMAP CONVERTED STATEMENT START */CREATE EXTENSION IF NOT EXISTS  dblink;
CREATE EXTENSION IF NOT EXISTS oracle_fdw;
CREATE SERVER DBLINK_2_SERVERS  FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host '192.168.1.18', port '1521');/* DMAP CONVERTED STATEMENT END */
