CREATE TABLE "DEMO"."ALL_BILL_RESOURCES" 
   (	"RESOURCE_ID" VARCHAR2(40), 
	"RESOURCE_DATA" BLOB, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"COMPRESSION_TYPE" VARCHAR2(2), 
	"UNCOMPRESSED_SIZE" NUMBER, 
	"COMPRESSED_SIZE" NUMBER, 
	"CHECKSUM" VARCHAR2(256), 
	"ORIG_RESOURCE_DATA" BLOB, 
	"ORIG_CHECKSUM" VARCHAR2(256)
   ) ;
