CREATE TABLE "DEMO"."DATAMIG" 
   (	"GRIEVANCE_STEPS_ATTENDEES_ID" NUMBER(38,2), 
	"GRIEVANCE_STEPS_ID" NUMBER(38,2), 
	"ATTENDEE_TYPE" VARCHAR2(1 CHAR), 
	"ATTENDEE_FIRST_NAME" VARCHAR2(30 CHAR), 
	"ATTENDEE_MIDDLE_INIT" VARCHAR2(1 CHAR), 
	"ATTENDEE_LAST_NAME" VARCHAR2(35 CHAR), 
	"ATTENDEE_JOB_TITLE" VARCHAR2(30 CHAR), 
	"ATTENDEE_PHONE_NUMBER" VARCHAR2(72 CHAR), 
	"MOD_USER" VARCHAR2(30 CHAR), 
	"MOD_DATE" DATE, 
	"CREATEDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 CHAR)
   ) ;
