CREATE TABLE "DEMO"."MD_APPLICATIONS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(4000), 
	"DESCRIPTION" VARCHAR2(4000), 
	"BASE_DIR" VARCHAR2(4000), 
	"OUTPUT_DIR" VARCHAR2(4000), 
	"BACKUP_DIR" VARCHAR2(4000), 
	"INPLACE" NUMBER, 
	"PROJECT_ID_FK" NUMBER NOT NULL ENABLE, 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255)
   ) ;
ALTER TABLE "DEMO"."MD_APPLICATIONS" ADD CONSTRAINT "MD_APPLICATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
