CREATE TABLE "DEMO"."MD_CONSTRAINTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DELETE_CLAUSE" VARCHAR2(4000), 
	"NAME" VARCHAR2(4000), 
	"CONSTRAINT_TYPE" VARCHAR2(4000), 
	"TABLE_ID_FK" NUMBER NOT NULL ENABLE, 
	"REFTABLE_ID_FK" NUMBER, 
	"CONSTRAINT_TEXT" CLOB, 
	"LANGUAGE" VARCHAR2(40) NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(4000), 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255)
   ) ;
