CREATE TABLE "DEMO"."MD_CATALOGS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CONNECTION_ID_FK" NUMBER NOT NULL ENABLE, 
	"CATALOG_NAME" VARCHAR2(4000), 
	"DUMMY_FLAG" CHAR(1) DEFAULT 'N', 
	"NATIVE_SQL" CLOB, 
	"NATIVE_KEY" VARCHAR2(4000), 
	"COMMENTS" VARCHAR2(4000), 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255)
   ) ;
ALTER TABLE "DEMO"."MD_CATALOGS" ADD CONSTRAINT "MD_CATALOGS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
