CREATE TABLE "DEMO"."MD_FILE_ARTIFACTS" 
   (	"ID" NUMBER CONSTRAINT "MD_APP_FILE_ART_NONULL" NOT NULL ENABLE, 
	"APPLICATIONFILES_ID" NUMBER CONSTRAINT "MD_APPL_FILE_FK_NONULL" NOT NULL ENABLE, 
	"PATTERN" VARCHAR2(4000), 
	"STRING_FOUND" VARCHAR2(4000), 
	"STRING_REPLACED" VARCHAR2(4000), 
	"TYPE" VARCHAR2(200), 
	"STATUS" VARCHAR2(4000), 
	"LINE" NUMBER, 
	"PATTERN_START" NUMBER, 
	"PATTERN_END" NUMBER, 
	"DUE_DATE" DATE, 
	"DB_TYPE" VARCHAR2(100), 
	"CODE_TYPE" VARCHAR2(1000), 
	"DESCRIPTION" VARCHAR2(4000), 
	"PRIORITY" NUMBER(*,0), 
	"SECURITY_GROUP_ID" VARCHAR2(20) DEFAULT '0' NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(4000), 
	"LAST_UPDATED" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(4000)
   ) ;
ALTER TABLE "DEMO"."MD_FILE_ARTIFACTS" ADD CONSTRAINT "MD_FILE_ARTIFACTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
