CREATE TABLE "DEMO"."MD_INDEX_DETAILS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"INDEX_ID_FK" NUMBER NOT NULL ENABLE, 
	"COLUMN_ID_FK" NUMBER NOT NULL ENABLE, 
	"INDEX_PORTION" NUMBER, 
	"DETAIL_ORDER" NUMBER NOT NULL ENABLE, 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255)
   ) ;
ALTER TABLE "DEMO"."MD_INDEX_DETAILS" ADD CONSTRAINT "MD_INDEX_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
