CREATE TABLE "DEMO"."MD_PROJECTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_NAME" VARCHAR2(4000) NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(4000), 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255)
   ) ;
ALTER TABLE "DEMO"."MD_PROJECTS" ADD CONSTRAINT "MD_PROJECTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
