CREATE TABLE "DEMO"."MD_PARTITIONS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TABLE_ID_FK" NUMBER NOT NULL ENABLE, 
	"NATIVE_SQL" CLOB, 
	"PARTITION_EXPRESSION" VARCHAR2(4000), 
	"COMMENTS" VARCHAR2(4000), 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE
   ) ;
ALTER TABLE "DEMO"."MD_PARTITIONS" ADD CONSTRAINT "MD_PARTITIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
