CREATE TABLE "DEMO"."MD_TABLESPACES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SCHEMA_ID_FK" NUMBER NOT NULL ENABLE, 
	"TABLESPACE_NAME" VARCHAR2(4000), 
	"NATIVE_SQL" CLOB, 
	"NATIVE_KEY" VARCHAR2(4000), 
	"COMMENTS" VARCHAR2(4000), 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255)
   ) ;
ALTER TABLE "DEMO"."MD_TABLESPACES" ADD CONSTRAINT "MD_TABLESPACES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
