CREATE TABLE "DEMO"."MD_USER_PRIVILEGES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USER_ID_FK" NUMBER NOT NULL ENABLE, 
	"PRIVILEGE_ID_FK" NUMBER, 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE, 
	"LAST_UDPATED_BY" VARCHAR2(255)
   ) ;
ALTER TABLE "DEMO"."MD_USER_PRIVILEGES" ADD CONSTRAINT "MD_USER_PRIVILEGES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
