CREATE TABLE "DEMO"."MEDICAL_BILLS_HISTORY" 
   (	"BILL_ID" NUMBER(10,0), 
	"BILL_NUMBER" VARCHAR2(20), 
	"PARTY_NAME" VARCHAR2(50), 
	"BILL_DATE" DATE, 
	"DELETED_BY" VARCHAR2(20), 
	"DELETED_DATE" DATE
   ) ;
