CREATE TABLE "DEMO"."ORDERS" 
   (	"ORDER_ID" NUMBER(5,0), 
	"QUANTITY" NUMBER(4,0), 
	"COST_PER_ITEM" NUMBER(6,2), 
	"TOTAL_COST" NUMBER(8,2), 
	"CREATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(10)
   ) ;
