CREATE TABLE "DEMO"."PROMO_ALLOCATION" 
   (	"CODE" NUMBER(12,0), 
	"NAME" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(500), 
	"BLOCKMSD" CHAR(1) DEFAULT 'N', 
	"ISPROMOSEND_BLOCKED" CHAR(1) DEFAULT 'N'
   ) ;
