CREATE TABLE "DEMO"."PSITE_LOCALPOLICY" 
   (	"CODE" NUMBER(12,0), 
	"NAME" VARCHAR2(100), 
	"REMARKS" VARCHAR2(500), 
	"CREATEDON" DATE, 
	"CREATEDBY" NUMBER(12,0), 
	"LASTMODIFIEDON" DATE, 
	"LASTMODIFIEDBY" NUMBER(12,0), 
	"DATAVERSION" NUMBER(12,0)
   ) ;
