CREATE TABLE "DEMO"."TIGGER_IDX" 
   (	"PROCEDURE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"FUNCTION_NAME" VARCHAR2(20), 
	"TRIGGER_ID" NUMBER(*,0), 
	"INDEX_NAME" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "DEMO"."TIGGER_IDX_PK" ON "DEMO"."TIGGER_IDX" ("PROCEDURE_ID") 
  ;
ALTER TABLE "DEMO"."TIGGER_IDX" ADD CONSTRAINT "TIGGER_IDX_PK" PRIMARY KEY ("PROCEDURE_ID")
  USING INDEX "DEMO"."TIGGER_IDX_PK"  ENABLE;
