CREATE OR REPLACE NONEDITIONABLE TRIGGER "DEMO"."EMP_VIEW_MODIFY_TRG" 
INSTEAD OF UPDATE
ON demo.emp_view
FOR EACH ROW
BEGIN
UPDATE dept
SET loc=:new.loc
WHERE loc =:old.loc;
END;
/
ALTER TRIGGER "DEMO"."EMP_VIEW_MODIFY_TRG" ENABLE;
