CREATE MATERIALIZED VIEW "YODA"."EMP_MV" ("COURSE_NO", "DESCRIPTION", "COST", "PREREQUISITE", "CREATED_BY", "CREATED_DATE", "MODIFIED_BY", "MODIFIED_DATE")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT * FROM COURSE@DB1.WORLD;
