CREATE OR REPLACE NONEDITIONABLE PACKAGE "DEMO"."DBMS_OUTPUT_PKG1" 
IS c_prefix CONSTANT CHAR(1) := '*'; 
c_linelen CONSTANT INTEGER := 80; 
PROCEDURE ln (val IN VARCHAR2); 
PROCEDURE ln (val IN DATE); 
PROCEDURE ln (val IN NUMBER); 
PROCEDURE ln (val IN BOOLEAN); 
END;
/
CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "DEMO"."DBMS_OUTPUT_PKG1" 
IS 
PROCEDURE 
ln (val IN VARCHAR2) 
IS 
BEGIN 
IF LENGTH (val) > 255 THEN 
--PLVprs.display_wrap (val, c_linelen); 
NULL;
ELSE DBMS_OUTPUT.PUT_LINE (c_prefix || val); 
END IF; 
EXCEPTION 
   WHEN OTHERS THEN 
   DBMS_OUTPUT.ENABLE (1000000); 
   DBMS_OUTPUT.PUT_LINE (c_prefix || val); 
   END; 

PROCEDURE ln (val IN DATE) 
IS 
BEGIN ln (TO_CHAR (val)); 
END; 

PROCEDURE ln (val IN NUMBER) 
IS 
BEGIN ln (TO_CHAR (val)); 
END; 

PROCEDURE ln (val IN BOOLEAN) 
IS 
BEGIN 
IF val THEN ln ('TRUE'); 
ELSIF NOT val THEN 
ln ('FALSE'); 
ELSE 
  ln ('NULL BOOLEAN'); 
END IF; 
END; 
END;
/;
