CREATE OR REPLACE EDITIONABLE PACKAGE "DEMO"."PRT" 
IS c_prefix CONSTANT CHAR(1) := '*'; 
c_linelen CONSTANT INTEGER := 80; 
PROCEDURE ln (val IN VARCHAR2); 
PROCEDURE ln (val IN DATE); 
PROCEDURE ln (val IN NUMBER); 
PROCEDURE ln (val IN BOOLEAN); 
END; 
/
;
