CREATE TABLE "YODA"."BFILE_ICONS" SHARING=METADATA 
   (	"ICON_ID" VARCHAR2(100) NOT NULL ENABLE, 
	"ICON_REL_PATH" VARCHAR2(1000), 
	"ICON_GRAPIC" BFILE
   ) ;
ALTER TABLE "YODA"."BFILE_ICONS" ADD PRIMARY KEY ("ICON_ID")
  USING INDEX  ENABLE;
