CREATE TABLE "YODA"."COURSE" SHARING=METADATA 
   (	"COURSE_NO" NUMBER(8,0) CONSTRAINT "CRSE_COURSE_NO_NNULL" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(50) CONSTRAINT "CRSE_DESCRIPTION_NNULL" NOT NULL ENABLE, 
	"COST" NUMBER(9,2), 
	"PREREQUISITE" NUMBER(8,0), 
	"CREATED_BY" VARCHAR2(30) CONSTRAINT "CRSE_CREATED_BY_NNULL" NOT NULL ENABLE, 
	"CREATED_DATE" DATE CONSTRAINT "CRSE_CREATED_DATE_NNULL" NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) CONSTRAINT "CRSE_MODIFIED_BY_NNULL" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE CONSTRAINT "CRSE_MODIFIED_DATE_NNULL" NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."COURSE" ADD CONSTRAINT "CRSE_PK" PRIMARY KEY ("COURSE_NO")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."COURSE" ADD CONSTRAINT "CRSE_CRSE_FK" FOREIGN KEY ("PREREQUISITE")
	  REFERENCES "YODA"."COURSE" ("COURSE_NO") ENABLE;
