CREATE TABLE "YODA"."DEST_TAB" SHARING=METADATA 
   (	"OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"OWNER" VARCHAR2(128) NOT NULL ENABLE, 
	"OBJECT_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"OBJECT_TYPE" VARCHAR2(23)
   ) ;
ALTER TABLE "YODA"."DEST_TAB" ADD CONSTRAINT "DEST_TAB_PK" PRIMARY KEY ("OBJECT_ID")
  USING INDEX  ENABLE;
