CREATE TABLE "YODA"."EMPLOYEE_DETAILS" SHARING=METADATA 
   (	"EMPLOYEE_ID" NUMBER, 
	"EMPLOYEE_NAME" VARCHAR2(10), 
	"EMPLOYEE_BRANCH_CODE" VARCHAR2(5), 
	"EMPLOYEE_MOBILE_NUMBER" NUMBER, 
	"EMPLOYEE_SALARY" NUMBER, 
	"EMPLOYEE_COMM" NUMBER, 
	"EMPLOYEE_JOIN_DATE" DATE
   ) ;
