CREATE TABLE "YODA"."EMPLOYEE_DETAILS_OUTER_JOIN" SHARING=METADATA 
   (	"EMPLOYEE_ID" NUMBER, 
	"EMPLOYEE_NAME" VARCHAR2(10), 
	"EMPLOYEE_BRANCH_CODE" VARCHAR2(5), 
	"EMPLOYEE_MOBILE_NUMBER" NUMBER, 
	"EMPLOYEE_SALARY" NUMBER, 
	"EMPLOYEE_COMM" NUMBER
   ) ;
