CREATE TABLE "YODA"."EMPLOYEE_AUDITS" SHARING=METADATA 
   (	"ID" NUMBER(*,0), 
	"EMPLOYEE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"CHANGED_ON" TIMESTAMP (6) NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."EMPLOYEE_AUDITS" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
