CREATE TABLE "YODA"."EMPLOYEE_DETAILS_NEW" SHARING=METADATA 
   (	"EMPLOYEE_ID" NUMBER, 
	"EMPLOYEE_NAME" VARCHAR2(10), 
	"EMPLOYEE_MOBILE_NUMBER" NUMBER, 
	"EMPLOYEE_BRANCH" VARCHAR2(10), 
	"EMPLOYEE_JOIN_DATE" DATE, 
	"EMPLOYEE_SALARY" NUMBER, 
	"EMPLOYEE_COMM" NUMBER
   ) ;
