CREATE TABLE "YODA"."EMPLOYEE_BKP" SHARING=METADATA 
   (	"EMP_ID" NUMBER, 
	"EMP_NAME" VARCHAR2(20), 
	"EMAIL_ID" VARCHAR2(20), 
	"DATE_OF_BIRTH" DATE, 
	"JOINING_DATE" DATE, 
	"SALARY" NUMBER(10,2), 
	"COMM" NUMBER(10,2), 
	"DEPARTMENT" VARCHAR2(10), 
	"MOBILE_NO" NUMBER, 
	"ADDRESS" VARCHAR2(20)
   ) ;
