CREATE TABLE "YODA"."EMPLOYEES" SHARING=METADATA 
   (	"ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(40) NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."EMPLOYEES" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
