CREATE TABLE "YODA"."ENROLLMENT" SHARING=METADATA 
   (	"STUDENT_ID" NUMBER(8,0) CONSTRAINT "ENR_STUDENT_ID_NNULL" NOT NULL ENABLE, 
	"SECTION_ID" NUMBER(8,0) CONSTRAINT "ENR_SECTION_ID_NNULL" NOT NULL ENABLE, 
	"ENROLL_DATE" DATE CONSTRAINT "ENR_ENROLL_DATE_NNULL" NOT NULL ENABLE, 
	"FINAL_GRADE" NUMBER(3,0), 
	"CREATED_BY" VARCHAR2(30) CONSTRAINT "ENR_CREATED_BY_NNULL" NOT NULL ENABLE, 
	"CREATED_DATE" DATE CONSTRAINT "ENR_CREATED_DATE_NNULL" NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) CONSTRAINT "ENR_MODIFIED_BY_NNULL" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE CONSTRAINT "ENR_MODIFIED_DATE_NNULL" NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."ENROLLMENT" ADD CONSTRAINT "ENR_PK" PRIMARY KEY ("STUDENT_ID", "SECTION_ID")
  USING INDEX  ENABLE;
