CREATE TABLE "YODA"."FULL_TEXT_SEARCH_TBL" SHARING=METADATA 
   (	"ID" NUMBER(16,0) NOT NULL ENABLE, 
	"ST_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CL_TRN_DATA" CLOB, 
	"AMOUNT" NUMBER(12,2) NOT NULL ENABLE, 
	"REFUND_AMOUNT" NUMBER(12,2), 
	"CURRENCY" CHAR(3) NOT NULL ENABLE, 
	"IP_ADDRESS" VARCHAR2(50), 
	"LK_DT" TIMESTAMP (6), 
	"LOCKED_BY" VARCHAR2(50), 
	"FORM_OF_PAYMENT" VARCHAR2(20) NOT NULL ENABLE, 
	"SEARCH_DATA" VARCHAR2(500), 
	"CREATION_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"MODIFICATION_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DISCRIMINATOR" VARCHAR2(10) DEFAULT 'CP' NOT NULL ENABLE, 
	"CHINA_PAY_FORM_OF_PAYMENT" VARCHAR2(20) DEFAULT 'TODO' NOT NULL ENABLE, 
	"PAYMENT_FOR_SERVICE" VARCHAR2(40) DEFAULT 'AIRBOOK' NOT NULL ENABLE, 
	"VERIFICATION_DATE" TIMESTAMP (6)
   ) ;
