CREATE TABLE "YODA"."GRADE_TYPE" SHARING=METADATA 
   (	"GRADE_TYPE_CODE" CHAR(2) CONSTRAINT "GRTYP_GRADE_TYPE_CODE_NNULL" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(50) CONSTRAINT "GRTYP_DESCRIPTION_NNULL" NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30) CONSTRAINT "GRTYP_CREATED_BY_NNULL" NOT NULL ENABLE, 
	"CREATED_DATE" DATE CONSTRAINT "GRTYP_CREATED_DATE_NNULL" NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) CONSTRAINT "GRTYP_MODIFIED_BY_NNULL" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE CONSTRAINT "GRTYP_MODIFIED_DATE_NNULL" NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."GRADE_TYPE" ADD CONSTRAINT "GRTYP_PK" PRIMARY KEY ("GRADE_TYPE_CODE")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."GRADE_TYPE" ADD CONSTRAINT "GRTYP_GRADE_TYPE_CODE_LENGTH" CHECK (LENGTH(grade_type_code)=2) ENABLE;
