CREATE TABLE "YODA"."GRADE" SHARING=METADATA 
   (	"STUDENT_ID" NUMBER(8,0) CONSTRAINT "GR_STUDENT_ID_NNULL" NOT NULL ENABLE, 
	"SECTION_ID" NUMBER(8,0) CONSTRAINT "GR_SECTION_ID_NNULL" NOT NULL ENABLE, 
	"GRADE_TYPE_CODE" CHAR(2) CONSTRAINT "GR_GRADE_TYPE_CODE_NNULL" NOT NULL ENABLE, 
	"GRADE_CODE_OCCURRENCE" NUMBER(38,0) CONSTRAINT "GR_GRADE_CODE_OCCURRENCE_NNULL" NOT NULL ENABLE, 
	"NUMERIC_GRADE" NUMBER(3,0) DEFAULT 0 CONSTRAINT "GR_NUMERIC_GRADE_NNULL" NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(2000), 
	"CREATED_BY" VARCHAR2(30) CONSTRAINT "GR_CREATED_BY_NNULL" NOT NULL ENABLE, 
	"CREATED_DATE" DATE CONSTRAINT "GR_CREATED_DATE_NNULL" NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) CONSTRAINT "GR_MODIFIED_BY_NNULL" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE CONSTRAINT "GR_MODIFIED_DATE_NNULL" NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."GRADE" ADD CONSTRAINT "GR_PK" PRIMARY KEY ("STUDENT_ID", "SECTION_ID", "GRADE_TYPE_CODE", "GRADE_CODE_OCCURRENCE")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."GRADE" ADD CONSTRAINT "GR_GRTW_FK" FOREIGN KEY ("SECTION_ID", "GRADE_TYPE_CODE")
	  REFERENCES "YODA"."GRADE_TYPE_WEIGHT" ("SECTION_ID", "GRADE_TYPE_CODE") ENABLE;
ALTER TABLE "YODA"."GRADE" ADD CONSTRAINT "GR_ENR_FK" FOREIGN KEY ("STUDENT_ID", "SECTION_ID")
	  REFERENCES "YODA"."ENROLLMENT" ("STUDENT_ID", "SECTION_ID") ENABLE;
