CREATE TABLE "YODA"."GRADE_TYPE_WEIGHT" SHARING=METADATA 
   (	"SECTION_ID" NUMBER(8,0) CONSTRAINT "GRTW_SECTION_ID_NNULL" NOT NULL ENABLE, 
	"GRADE_TYPE_CODE" CHAR(2) CONSTRAINT "GRTW_GRADE_TYPE_CODE_NNULL" NOT NULL ENABLE, 
	"NUMBER_PER_SECTION" NUMBER(3,0) CONSTRAINT "GRTW_NUMBER_PER_SECTION_NNULL" NOT NULL ENABLE, 
	"PERCENT_OF_FINAL_GRADE" NUMBER(3,0) CONSTRAINT "GRTW_PCT_OF_FINAL_GRADE_NNULL" NOT NULL ENABLE, 
	"DROP_LOWEST" CHAR(1) CONSTRAINT "GRTW_DROP_LOWEST_NNULL" NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30) CONSTRAINT "GRTW_CREATED_BY_NNULL" NOT NULL ENABLE, 
	"CREATED_DATE" DATE CONSTRAINT "GRTW_CREATED_DATE_NNULL" NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) CONSTRAINT "GRTW_MODIFIED_BY_NNULL" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE CONSTRAINT "GRTW_MODIFIED_DATE_NNULL" NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."GRADE_TYPE_WEIGHT" ADD CONSTRAINT "GRTW_PK" PRIMARY KEY ("SECTION_ID", "GRADE_TYPE_CODE")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."GRADE_TYPE_WEIGHT" ADD CONSTRAINT "GRTW_SECT_FK" FOREIGN KEY ("SECTION_ID")
	  REFERENCES "YODA"."SECTION" ("SECTION_ID") ENABLE;
ALTER TABLE "YODA"."GRADE_TYPE_WEIGHT" ADD CONSTRAINT "GRTW_GRTYP_FK" FOREIGN KEY ("GRADE_TYPE_CODE")
	  REFERENCES "YODA"."GRADE_TYPE" ("GRADE_TYPE_CODE") ENABLE;
