CREATE TABLE "YODA"."GRADE_CONVERSION" SHARING=METADATA 
   (	"LETTER_GRADE" VARCHAR2(2) CONSTRAINT "GRCON_LETTER_GRADE_NNULL" NOT NULL ENABLE, 
	"GRADE_POINT" NUMBER(3,2) DEFAULT 0 CONSTRAINT "GRCON_GRADE_POINT_NNULL" NOT NULL ENABLE, 
	"MAX_GRADE" NUMBER(3,0) CONSTRAINT "GRCON_MAX_GRADE_NNULL" NOT NULL ENABLE, 
	"MIN_GRADE" NUMBER(3,0) CONSTRAINT "GRCON_MIN_GRADE_NNULL" NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30) CONSTRAINT "GRCON_CREATED_BY_NNULL" NOT NULL ENABLE, 
	"CREATED_DATE" DATE CONSTRAINT "GRCON_CREATED_DATE_NNULL" NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) CONSTRAINT "GRCON_MODIFIED_BY_NNULL" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE CONSTRAINT "GRCON_MODIFIED_DATE_NNULL" NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."GRADE_CONVERSION" ADD CONSTRAINT "GRCON_PK" PRIMARY KEY ("LETTER_GRADE")
  USING INDEX  ENABLE;
