CREATE TABLE "YODA"."INSTRUCTOR" SHARING=METADATA 
   (	"INSTRUCTOR_ID" NUMBER(8,0) CONSTRAINT "INST_INSTRUCTOR_ID_NNULL" NOT NULL ENABLE, 
	"SALUTATION" VARCHAR2(5), 
	"FIRST_NAME" VARCHAR2(25), 
	"LAST_NAME" VARCHAR2(25), 
	"STREET_ADDRESS" VARCHAR2(50), 
	"ZIP" VARCHAR2(5), 
	"PHONE" VARCHAR2(15), 
	"CREATED_BY" VARCHAR2(30) CONSTRAINT "INST_CREATED_BY_NNULL" NOT NULL ENABLE, 
	"CREATED_DATE" DATE CONSTRAINT "INST_CREATED_DATE_NNULL" NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) CONSTRAINT "INST_MODFIED_BY_NNULL" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE CONSTRAINT "INST_MODIFIED_DATE_NNULL" NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."INSTRUCTOR" ADD CONSTRAINT "INST_PK" PRIMARY KEY ("INSTRUCTOR_ID")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."INSTRUCTOR" ADD CONSTRAINT "INST_ZIP_FK" FOREIGN KEY ("ZIP")
	  REFERENCES "YODA"."ZIPCODE" ("ZIP") ENABLE;
