CREATE TABLE "YODA"."INTERVAL_SALES" SHARING=METADATA 
   (	"PROD_ID" NUMBER(6,0), 
	"CUST_ID" NUMBER, 
	"TIME_ID" DATE, 
	"CHANNEL_ID" CHAR(1), 
	"PROMO_ID" NUMBER(6,0), 
	"QUANTITY_SOLD" NUMBER(3,0), 
	"AMOUNT_SOLD" NUMBER(10,2)
   ) 
  PARTITION BY RANGE ("TIME_ID") INTERVAL (NUMTOYMINTERVAL(1, 'MONTH')) 
 (PARTITION "P0"  VALUES LESS THAN (TO_DATE(' 2008-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , 
 PARTITION "P1"  VALUES LESS THAN (TO_DATE(' 2009-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , 
 PARTITION "P2"  VALUES LESS THAN (TO_DATE(' 2009-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , 
 PARTITION "P3"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
