CREATE TABLE "YODA"."INTERVAL_TAB" SHARING=METADATA 
   (	"ID" NUMBER, 
	"CODE" VARCHAR2(10), 
	"DESCRIPTION" VARCHAR2(50), 
	"CREATED_DATE" DATE
   ) 
  PARTITION BY RANGE ("CREATED_DATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) 
 (PARTITION "PART_01"  VALUES LESS THAN (TO_DATE(' 2007-11-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
