CREATE TABLE "YODA"."INVOICES_HASH" SHARING=METADATA 
   (	"INVOICE_NO" NUMBER NOT NULL ENABLE, 
	"INVOICE_DATE" DATE NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(500)
   ) 
  PARTITION BY HASH ("INVOICE_NO") 
 (PARTITION "INVOICES_Q1" , 
 PARTITION "INVOICES_Q2" , 
 PARTITION "INVOICES_Q3" , 
 PARTITION "INVOICES_Q4" ) ;
