CREATE TABLE "YODA"."LOB_TAB" SHARING=METADATA 
   (	"NUMBER_CONTENT" NUMBER(10,0), 
	"VARCHAR2_CONTENT" VARCHAR2(10), 
	"CLOB_CONTENT" CLOB
   ) ;
ALTER TABLE "YODA"."LOB_TAB" ADD CONSTRAINT "LOB_TAB_PK" PRIMARY KEY ("NUMBER_CONTENT")
  USING INDEX  ENABLE;
