-- dmap_object_gen_tag : type : table name : mlb_data
set search_path = yoda,oracle,dmap_extension,public;
create table "mlb_data"  (
mlb_id numeric,
mlb_name varchar(30),
mlb_pos varchar(30),
mlb_team varchar(30),
mlb_team_long varchar(30),
bats varchar(30),
throws varchar(30),
birth_year varchar(30),
bp_id numeric,
bref_id varchar(30),
bref_name varchar(30),
cbs_id varchar(30),
cbs_name varchar(30),
cbs_pos varchar(30),
espn_id numeric,
espn_name varchar(30),
espn_pos varchar(30),
fg_id varchar(30),
fg_name varchar(30),
lahman_id varchar(30),
nfbc_id numeric,
nfbc_name varchar(30),
nfbc_pos varchar(30),
retro_id varchar(30),
retro_name varchar(30),
debut varchar(30),
yahoo_id numeric,
yahoo_name varchar(30),
yahoo_pos varchar(30),
mlb_depth varchar(30)
) ;
