CREATE TABLE "YODA"."NAME_DATA" SHARING=METADATA 
   (	"NAME_TYPE" VARCHAR2(15) NOT NULL ENABLE, 
	"NAME" VARCHAR2(45) NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."NAME_DATA" ADD CONSTRAINT "NAME_DATA_PK" PRIMARY KEY ("NAME_TYPE", "NAME")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."NAME_DATA" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
