CREATE TABLE "YODA"."NFL_DATA" SHARING=METADATA 
   (	"POSITION" VARCHAR2(5), 
	"PLAYER_NUMBER" NUMBER(3,0), 
	"NAME" VARCHAR2(40), 
	"STATUS" VARCHAR2(10), 
	"STAT1" VARCHAR2(10), 
	"STAT1_VAL" VARCHAR2(10), 
	"STAT2" VARCHAR2(10), 
	"STAT2_VAL" VARCHAR2(10), 
	"STAT3" VARCHAR2(10), 
	"STAT3_VAL" VARCHAR2(10), 
	"STAT4" VARCHAR2(10), 
	"STAT4_VAL" VARCHAR2(10), 
	"TEAM" VARCHAR2(10)
   ) ;
ALTER TABLE "YODA"."NFL_DATA" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
