CREATE TABLE "YODA"."NFL_STADIUM_DATA" SHARING=METADATA 
   (	"STADIUM" VARCHAR2(60), 
	"SEATING_CAPACITY" NUMBER, 
	"LOCATION" VARCHAR2(40), 
	"SURFACE" VARCHAR2(80), 
	"ROOF" VARCHAR2(30), 
	"TEAM" VARCHAR2(40), 
	"OPENED" VARCHAR2(10), 
	"SPORT_LOCATION_ID" NUMBER
   ) ;
ALTER TABLE "YODA"."NFL_STADIUM_DATA" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
