CREATE TABLE "YODA"."ORDER_ITEMS" SHARING=METADATA 
   (	"ORDER_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"LINE_ITEM_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER(8,2), 
	"QUANTITY" NUMBER(8,0), 
	 CONSTRAINT "ORDER_ITEMS_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "YODA"."ORDERS" ("ORDER_ID") ENABLE
   ) 
  PARTITION BY REFERENCE ("ORDER_ITEMS_FK") 
 (PARTITION "Q1_2005" , 
 PARTITION "Q2_2005" , 
 PARTITION "Q3_2005" , 
 PARTITION "Q4_2005" ) ;
