CREATE TABLE "YODA"."ORDERS_M" SHARING=METADATA 
   (	"ID" NUMBER, 
	"COUNTRY_CODE" VARCHAR2(5), 
	"CUSTOMER_ID" NUMBER, 
	"ORDER_DATE" DATE, 
	"ORDER_TOTAL" NUMBER(8,2)
   ) 
  PARTITION BY LIST ("COUNTRY_CODE") 
 (PARTITION "PART_USA"  VALUES ('USA') , 
 PARTITION "PART_UK_AND_IRELAND"  VALUES ('GBR', 'IRL') ) ;
ALTER TABLE "YODA"."ORDERS_M" ADD CONSTRAINT "ORDERS_M_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
