CREATE TABLE "YODA"."ORDERS_LIST_DEFAULT" SHARING=METADATA 
   (	"ID" NUMBER, 
	"COUNTRY_CODE" VARCHAR2(5), 
	"CUSTOMER_ID" NUMBER, 
	"ORDER_DATE" DATE, 
	"ORDER_TOTAL" NUMBER(8,2)
   ) 
  PARTITION BY LIST ("COUNTRY_CODE") 
 (PARTITION "PART_DEF_USA"  VALUES ('USA') , 
 PARTITION "PART_DEF_UK_AND_IRELAND"  VALUES ('GBR', 'IRL') , 
 PARTITION "PART_DEF"  VALUES (DEFAULT) ) ;
ALTER TABLE "YODA"."ORDERS_LIST_DEFAULT" ADD CONSTRAINT "ORDERS_DEF_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
