CREATE TABLE "YODA"."PERSON" SHARING=METADATA 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(60) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(30), 
	"FIRST_NAME" VARCHAR2(30)
   ) ;
ALTER TABLE "YODA"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."PERSON" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
