CREATE TABLE "YODA"."PLAYER" SHARING=METADATA 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SPORT_TEAM_ID" NUMBER NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(30), 
	"FIRST_NAME" VARCHAR2(30), 
	"FULL_NAME" VARCHAR2(30)
   ) ;
ALTER TABLE "YODA"."PLAYER" ADD CONSTRAINT "PLAYER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."PLAYER" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE "YODA"."PLAYER" ADD CONSTRAINT "SPORT_TEAM_FK" FOREIGN KEY ("SPORT_TEAM_ID")
	  REFERENCES "YODA"."SPORT_TEAM" ("ID") ENABLE;
