CREATE TABLE "YODA"."SALE_STATS" SHARING=METADATA 
   (	"ID" NUMBER(*,0), 
	"FISCAL_YEAR" NUMBER(*,0), 
	"PRODUCT_A" NUMBER(*,0), 
	"PRODUCT_B" NUMBER(*,0), 
	"PRODUCT_C" NUMBER(*,0)
   ) ;
ALTER TABLE "YODA"."SALE_STATS" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
