CREATE TABLE "YODA"."SALE_STATS_REPORT" SHARING=METADATA 
   (	"ID" NUMBER(*,0), 
	"FISCAL_YEAR" NUMBER(*,0), 
	"PRODUCT_CODE" CHAR(1), 
	"QUANTITY" NUMBER(*,0)
   ) ;
ALTER TABLE "YODA"."SALE_STATS_REPORT" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
