CREATE TABLE "YODA"."SAMPLE_USER_ACTION" SHARING=METADATA 
   (	"SAMPLE_USER_ACTION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SAMPLE_USER_ACTION_STATE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SAMPLE_USER_ACTION_TYPE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CA_ASSET_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PROCESSING_SEQ_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"SAMPLE_USER_ACTION_CLASS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"LAST_CHG_USER_NM" VARCHAR2(30) DEFAULT USER NOT NULL ENABLE, 
	"LAST_CHG_DT_TM" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CREATED_BY_USER_NM" VARCHAR2(30) DEFAULT USER NOT NULL ENABLE, 
	"CREATED_DT_TM" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATA_SOURCE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"EX_DT" NUMBER(*,0) NOT NULL ENABLE, 
	"RECORD_DT" NUMBER(*,0), 
	"PAY_DT" NUMBER(*,0), 
	"DATA_SOURCE_CA_EXT_ID" VARCHAR2(32), 
	"DESCRIPTION" VARCHAR2(2000), 
	"RECEIPT_ASSET_ID" NUMBER(*,0), 
	"GROSS_RECEIPT_FACTOR_AMT" NUMBER, 
	"NET_RECEIPT_FACTOR_AMT" NUMBER, 
	"RECEIPT_SYMBOL" VARCHAR2(20)
   ) ;
ALTER TABLE "YODA"."SAMPLE_USER_ACTION" ADD CONSTRAINT "PK_SAMPLE_USER_ACTION" PRIMARY KEY ("SAMPLE_USER_ACTION_ID")
  USING INDEX  ENABLE;
