CREATE TABLE "YODA"."SEAT_TYPE" SHARING=METADATA 
   (	"NAME" VARCHAR2(15) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120), 
	"RELATIVE_QUALITY" NUMBER(2,0)
   ) ;
ALTER TABLE "YODA"."SEAT_TYPE" ADD CONSTRAINT "ST_SEAT_TYPE_PK" PRIMARY KEY ("NAME")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SEAT_TYPE" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
