CREATE TABLE "YODA"."SEAT" SHARING=METADATA 
   (	"SPORT_LOCATION_ID" NUMBER, 
	"SEAT_LEVEL" NUMBER(1,0), 
	"SEAT_SECTION" VARCHAR2(15), 
	"SEAT_ROW" VARCHAR2(10), 
	"SEAT" VARCHAR2(10), 
	"SEAT_TYPE" VARCHAR2(15)
   ) ;
ALTER TABLE "YODA"."SEAT" ADD CONSTRAINT "SEAT_PK" PRIMARY KEY ("SPORT_LOCATION_ID", "SEAT_LEVEL", "SEAT_SECTION", "SEAT_ROW", "SEAT")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SEAT" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE "YODA"."SEAT" ADD CONSTRAINT "S_SPORT_LOCATION_FK" FOREIGN KEY ("SPORT_LOCATION_ID")
	  REFERENCES "YODA"."SPORT_LOCATION" ("ID") ENABLE;
ALTER TABLE "YODA"."SEAT" ADD CONSTRAINT "SEAT_TYPE_FK" FOREIGN KEY ("SEAT_TYPE")
	  REFERENCES "YODA"."SEAT_TYPE" ("NAME") ENABLE;
