CREATE TABLE "YODA"."SECTION" SHARING=METADATA 
   (	"SECTION_ID" NUMBER(8,0) CONSTRAINT "SECT_SECTION_ID_NNULL" NOT NULL ENABLE, 
	"COURSE_NO" NUMBER(8,0) CONSTRAINT "SECT_COURSE_NO_NNULL" NOT NULL ENABLE, 
	"SECTION_NO" NUMBER(3,0) CONSTRAINT "SECT_SECTION_NO_NNULL" NOT NULL ENABLE, 
	"START_DATE_TIME" DATE, 
	"LOCATION" VARCHAR2(50), 
	"INSTRUCTOR_ID" NUMBER(8,0) CONSTRAINT "SECT_INSTRUCTOR_ID_NNULL" NOT NULL ENABLE, 
	"CAPACITY" NUMBER(3,0), 
	"CREATED_BY" VARCHAR2(30) CONSTRAINT "SECT_CREATED_BY_NNULL" NOT NULL ENABLE, 
	"CREATED_DATE" DATE CONSTRAINT "SECT_CREATED_DATE_NNULL" NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) CONSTRAINT "SECT_MODIFIED_BY_NNULL" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE CONSTRAINT "SECT_MODIFIED_DATE_NNULL" NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."SECTION" ADD CONSTRAINT "SECT_SECT2_UK" UNIQUE ("SECTION_NO", "COURSE_NO")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SECTION" ADD CONSTRAINT "SECT_PK" PRIMARY KEY ("SECTION_ID")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SECTION" ADD CONSTRAINT "SECT_INST_FK" FOREIGN KEY ("INSTRUCTOR_ID")
	  REFERENCES "YODA"."INSTRUCTOR" ("INSTRUCTOR_ID") ENABLE;
ALTER TABLE "YODA"."SECTION" ADD CONSTRAINT "SECT_CRSE_FK" FOREIGN KEY ("COURSE_NO")
	  REFERENCES "YODA"."COURSE" ("COURSE_NO") ENABLE;
