CREATE TABLE "YODA"."SPORT_DIVISION" SHARING=METADATA 
   (	"SPORT_TYPE_NAME" VARCHAR2(15) NOT NULL ENABLE, 
	"SPORT_LEAGUE_SHORT_NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"SHORT_NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"LONG_NAME" VARCHAR2(60), 
	"DESCRIPTION" VARCHAR2(120)
   ) ;
ALTER TABLE "YODA"."SPORT_DIVISION" ADD CONSTRAINT "SPORT_DIVISION_PK" PRIMARY KEY ("SPORT_TYPE_NAME", "SPORT_LEAGUE_SHORT_NAME", "SHORT_NAME")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SPORT_DIVISION" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE "YODA"."SPORT_DIVISION" ADD CONSTRAINT "SD_SPORT_LEAGUE_FK" FOREIGN KEY ("SPORT_LEAGUE_SHORT_NAME")
	  REFERENCES "YODA"."SPORT_LEAGUE" ("SHORT_NAME") ENABLE;
ALTER TABLE "YODA"."SPORT_DIVISION" ADD CONSTRAINT "SD_SPORT_TYPE_FK" FOREIGN KEY ("SPORT_TYPE_NAME")
	  REFERENCES "YODA"."SPORT_TYPE" ("NAME") ENABLE;
