CREATE TABLE "YODA"."SPORT_TEAM" SHARING=METADATA 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"ABBREVIATED_NAME" VARCHAR2(10), 
	"HOME_FIELD_ID" NUMBER(3,0), 
	"SPORT_TYPE_NAME" VARCHAR2(15) NOT NULL ENABLE, 
	"SPORT_LEAGUE_SHORT_NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"SPORT_DIVISION_SHORT_NAME" VARCHAR2(10)
   ) ;
ALTER TABLE "YODA"."SPORT_TEAM" ADD CONSTRAINT "SPORT_TEAM_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SPORT_TEAM" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE "YODA"."SPORT_TEAM" ADD CONSTRAINT "ST_SPORT_TYPE_FK" FOREIGN KEY ("SPORT_TYPE_NAME")
	  REFERENCES "YODA"."SPORT_TYPE" ("NAME") ENABLE;
ALTER TABLE "YODA"."SPORT_TEAM" ADD CONSTRAINT "HOME_FIELD_FK" FOREIGN KEY ("HOME_FIELD_ID")
	  REFERENCES "YODA"."SPORT_LOCATION" ("ID") ENABLE;
