CREATE TABLE "YODA"."SPORT_TYPE" SHARING=METADATA 
   (	"NAME" VARCHAR2(15) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120)
   ) ;
ALTER TABLE "YODA"."SPORT_TYPE" ADD CONSTRAINT "SPORT_TYPE_PK" PRIMARY KEY ("NAME")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SPORT_TYPE" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
