CREATE TABLE "YODA"."SPORT_LOCATION" SHARING=METADATA 
   (	"ID" NUMBER(3,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(60) NOT NULL ENABLE, 
	"CITY" VARCHAR2(60) NOT NULL ENABLE, 
	"SEATING_CAPACITY" NUMBER(7,0), 
	"LEVELS" NUMBER(1,0), 
	"SECTIONS" NUMBER(4,0)
   ) ;
ALTER TABLE "YODA"."SPORT_LOCATION" ADD CONSTRAINT "SPORT_LOCATION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SPORT_LOCATION" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
