CREATE TABLE "YODA"."SPORTING_EVENT_TICKET" SHARING=METADATA 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SPORTING_EVENT_ID" NUMBER NOT NULL ENABLE, 
	"SPORT_LOCATION_ID" NUMBER NOT NULL ENABLE, 
	"SEAT_LEVEL" NUMBER(1,0) NOT NULL ENABLE, 
	"SEAT_SECTION" VARCHAR2(15) NOT NULL ENABLE, 
	"SEAT_ROW" VARCHAR2(10) NOT NULL ENABLE, 
	"SEAT" VARCHAR2(10) NOT NULL ENABLE, 
	"TICKETHOLDER_ID" NUMBER, 
	"TICKET_PRICE" NUMBER(8,2) NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."SPORTING_EVENT_TICKET" ADD CONSTRAINT "SPORTING_EVENT_TICKET_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SPORTING_EVENT_TICKET" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE "YODA"."SPORTING_EVENT_TICKET" ADD CONSTRAINT "SET_SPORTING_EVENT_FK" FOREIGN KEY ("SPORTING_EVENT_ID")
	  REFERENCES "YODA"."SPORTING_EVENT" ("ID") ENABLE;
ALTER TABLE "YODA"."SPORTING_EVENT_TICKET" ADD CONSTRAINT "SET_PERSON_ID" FOREIGN KEY ("TICKETHOLDER_ID")
	  REFERENCES "YODA"."PERSON" ("ID") ENABLE;
ALTER TABLE "YODA"."SPORTING_EVENT_TICKET" ADD CONSTRAINT "SET_SEAT_FK" FOREIGN KEY ("SPORT_LOCATION_ID", "SEAT_LEVEL", "SEAT_SECTION", "SEAT_ROW", "SEAT")
	  REFERENCES "YODA"."SEAT" ("SPORT_LOCATION_ID", "SEAT_LEVEL", "SEAT_SECTION", "SEAT_ROW", "SEAT") ENABLE;
