CREATE TABLE "YODA"."SPORTING_EVENT" SHARING=METADATA 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SPORT_TYPE_NAME" VARCHAR2(15) NOT NULL ENABLE, 
	"HOME_TEAM_ID" NUMBER NOT NULL ENABLE, 
	"AWAY_TEAM_ID" NUMBER NOT NULL ENABLE, 
	"LOCATION_ID" NUMBER NOT NULL ENABLE, 
	"START_DATE_TIME" DATE NOT NULL ENABLE, 
	"SOLD_OUT" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."SPORTING_EVENT" ADD CONSTRAINT "CHK_SOLD_OUT" CHECK (sold_out IN (0,1)) ENABLE;
ALTER TABLE "YODA"."SPORTING_EVENT" ADD CONSTRAINT "SPORTING_EVENT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SPORTING_EVENT" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE "YODA"."SPORTING_EVENT" ADD CONSTRAINT "SE_SPORT_TYPE_FK" FOREIGN KEY ("SPORT_TYPE_NAME")
	  REFERENCES "YODA"."SPORT_TYPE" ("NAME") ENABLE;
ALTER TABLE "YODA"."SPORTING_EVENT" ADD CONSTRAINT "SE_LOCATION_ID_FK" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "YODA"."SPORT_LOCATION" ("ID") ENABLE;
ALTER TABLE "YODA"."SPORTING_EVENT" ADD CONSTRAINT "SE_HOME_TEAM_ID_FK" FOREIGN KEY ("HOME_TEAM_ID")
	  REFERENCES "YODA"."SPORT_TEAM" ("ID") ENABLE;
ALTER TABLE "YODA"."SPORTING_EVENT" ADD CONSTRAINT "SE_AWAY_TEAM_ID_FK" FOREIGN KEY ("AWAY_TEAM_ID")
	  REFERENCES "YODA"."SPORT_TEAM" ("ID") ENABLE;
