CREATE TABLE "YODA"."SPORT_LEAGUE" SHARING=METADATA 
   (	"SPORT_TYPE_NAME" VARCHAR2(15) NOT NULL ENABLE, 
	"SHORT_NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"LONG_NAME" VARCHAR2(60) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120)
   ) ;
ALTER TABLE "YODA"."SPORT_LEAGUE" ADD CONSTRAINT "SPORT_LEAGUE_PK" PRIMARY KEY ("SHORT_NAME")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."SPORT_LEAGUE" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE "YODA"."SPORT_LEAGUE" ADD CONSTRAINT "SL_SPORT_TYPE_FK" FOREIGN KEY ("SPORT_TYPE_NAME")
	  REFERENCES "YODA"."SPORT_TYPE" ("NAME") ENABLE;
