-- dmap_object_gen_tag : type : table name : stadium_notes
set search_path = yoda,oracle,dmap_extension,public;/* dmap converted statement start */
create table "stadium_notes"  (
id bigint generated by default as identity (start with 1 increment by 1 maxvalue 9223372036854775807 minvalue 1 no cycle cache 20 ),
owner varchar(128),
"name" varchar(128),
type varchar(12),
line numeric,
text varchar(4000),
origin_con_id numeric
) partition by range (
id
) ;/* dmap converted statement end */
-- dmap_object_gen_tag : type : alter table name : stadium_notes
set search_path = yoda,oracle,dmap_extension,public;
alter table stadium_notes add constraint stadium_notes_pk primary key (id);
-- dmap_object_gen_tag : type : alter table name : stadium_notes
set search_path = yoda,oracle,dmap_extension,public;
alter table stadium_notes alter column id set not null;
