CREATE TABLE "YODA"."STUDENT" SHARING=METADATA 
   (	"STUDENT_ID" NUMBER(8,0) CONSTRAINT "STU_STUDENT_ID_NNULL" NOT NULL ENABLE, 
	"SALUTATION" VARCHAR2(5), 
	"FIRST_NAME" VARCHAR2(25), 
	"LAST_NAME" VARCHAR2(25) CONSTRAINT "STU_LAST_NAME_NNULL" NOT NULL ENABLE, 
	"STREET_ADDRESS" VARCHAR2(50), 
	"ZIP" VARCHAR2(5) CONSTRAINT "STU_ZIP_NNULL" NOT NULL ENABLE, 
	"PHONE" VARCHAR2(15), 
	"EMPLOYER" VARCHAR2(50), 
	"REGISTRATION_DATE" DATE CONSTRAINT "STU_REGISTRATION_DATE_NNULL" NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30) CONSTRAINT "STU_CREATED_BY_NNULL" NOT NULL ENABLE, 
	"CREATED_DATE" DATE CONSTRAINT "STU_CREATED_DATE_NNULL" NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) CONSTRAINT "STU_MODIFIED_BY_NNULL" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE CONSTRAINT "STU_MODIFIED_DATE_NNULL" NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."STUDENT" ADD CONSTRAINT "STU_PK" PRIMARY KEY ("STUDENT_ID")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."STUDENT" ADD CONSTRAINT "STU_ZIP_FK" FOREIGN KEY ("ZIP")
	  REFERENCES "YODA"."ZIPCODE" ("ZIP") ENABLE;
