CREATE TABLE "YODA"."TAB1" SHARING=METADATA 
   (	"ID" NUMBER, 
	"PARENT_ID" NUMBER
   ) ;
ALTER TABLE "YODA"."TAB1" ADD CONSTRAINT "TAB1_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."TAB1" ADD CONSTRAINT "TAB1_TAB1_FK" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "YODA"."TAB1" ("ID") ENABLE;
