-- dmap_object_gen_tag : type : table name : tables_info
set search_path = yoda,oracle,dmap_extension,public;
create table "tables_info"  (
table_name varchar(128) not null,
tablespace_name varchar(30),
cluster_name varchar(128),
iot_name varchar(128),
status varchar(8),
pct_free numeric,
pct_used numeric,
ini_trans numeric,
max_trans numeric,
initial_extent numeric,
next_extent numeric,
min_extents numeric,
max_extents numeric,
pct_increase numeric,
freelists numeric,
freelist_groups numeric,
logging varchar(3),
backed_up varchar(1),
num_rows numeric,
blocks numeric,
empty_blocks numeric,
avg_space numeric,
chain_cnt numeric,
avg_row_len numeric,
avg_space_freelist_blocks numeric,
num_freelist_blocks numeric,
degree varchar(40),
instances varchar(40),
cache varchar(20),
table_lock varchar(8),
sample_size numeric,
last_analyzed timestamp(0),
partitioned varchar(3),
iot_type varchar(12),
temporary varchar(1),
secondary varchar(1),
nested varchar(3),
buffer_pool varchar(7),
flash_cache varchar(7),
cell_flash_cache varchar(7),
row_movement varchar(8),
global_stats varchar(3),
user_stats varchar(3),
duration varchar(15),
skip_corrupt varchar(8),
monitoring varchar(3),
cluster_owner varchar(128),
dependencies varchar(8),
compression varchar(8),
compress_for varchar(30),
dropped varchar(3),
read_only varchar(3),
segment_created varchar(3),
result_cache varchar(7),
clustering varchar(3),
activity_tracking varchar(23),
dml_timestamp varchar(25),
has_identity varchar(3),
container_data varchar(3),
inmemory varchar(8),
inmemory_priority varchar(8),
inmemory_distribute varchar(15),
inmemory_compression varchar(17),
inmemory_duplicate varchar(13)
) ;
-- dmap_object_gen_tag : type : alter table name : tables_info
set search_path = yoda,oracle,dmap_extension,public;
alter table tables_info alter column table_name set not null;
