CREATE TABLE "YODA"."TEST_INDEX_2" SHARING=METADATA 
   (	"COL_1" NUMBER, 
	"COL_2" DATE, 
	"COL_3" VARCHAR2(1), 
	"COL_4" DATE
   ) ;
ALTER TABLE "YODA"."TEST_INDEX_2" ADD CONSTRAINT "FK_TEST_INDEX_2" FOREIGN KEY ("COL_1")
	  REFERENCES "YODA"."TEST_INDEX_1" ("COL_1") ENABLE;
