CREATE TABLE "YODA"."TEST_INDEX_1" SHARING=METADATA 
   (	"COL_1" NUMBER, 
	"COL_2" DATE, 
	"COL_3" VARCHAR2(1)
   ) ;
ALTER TABLE "YODA"."TEST_INDEX_1" ADD CONSTRAINT "TEST_INDEX_1_PK" PRIMARY KEY ("COL_1")
  USING INDEX  ENABLE;
