CREATE TABLE "YODA"."TICKETS_HASH_PARTITION" SHARING=METADATA 
   (	"TICKET_NO" NUMBER(18,0) NOT NULL ENABLE, 
	"TICKET_DATE" DATE NOT NULL ENABLE, 
	"REASON" VARCHAR2(20)
   ) 
  PARTITION BY HASH ("TICKET_NO") 
 (PARTITION "TICKETS_HASH_PARTITION_Q1" , 
 PARTITION "TICKETS_HASH_PARTITION_Q2" , 
 PARTITION "TICKETS_HASH_PARTITION_Q3" , 
 PARTITION "TICKETS_HASH_PARTITION_Q4" ) ;
ALTER TABLE "YODA"."TICKETS_HASH_PARTITION" ADD PRIMARY KEY ("TICKET_NO")
  USING INDEX  ENABLE;
