CREATE TABLE "YODA"."TICKET_PURCHASE_HIST" SHARING=METADATA 
   (	"SPORTING_EVENT_TICKET_ID" NUMBER NOT NULL ENABLE, 
	"PURCHASED_BY_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_DATE_TIME" DATE NOT NULL ENABLE, 
	"TRANSFERRED_FROM_ID" NUMBER, 
	"PURCHASE_PRICE" NUMBER(8,2) NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."TICKET_PURCHASE_HIST" ADD CONSTRAINT "TICKET_PURCHASE_HIST_PK" PRIMARY KEY ("SPORTING_EVENT_TICKET_ID", "PURCHASED_BY_ID", "TRANSACTION_DATE_TIME")
  USING INDEX  ENABLE;
ALTER TABLE "YODA"."TICKET_PURCHASE_HIST" ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE "YODA"."TICKET_PURCHASE_HIST" ADD CONSTRAINT "TPH_TICKETHOLDER_ID" FOREIGN KEY ("PURCHASED_BY_ID")
	  REFERENCES "YODA"."PERSON" ("ID") ENABLE;
ALTER TABLE "YODA"."TICKET_PURCHASE_HIST" ADD CONSTRAINT "TPH_SPORT_EVENT_TIC_ID" FOREIGN KEY ("SPORTING_EVENT_TICKET_ID")
	  REFERENCES "YODA"."SPORTING_EVENT_TICKET" ("ID") ENABLE;
ALTER TABLE "YODA"."TICKET_PURCHASE_HIST" ADD CONSTRAINT "TPH_TRANSFER_FROM_ID" FOREIGN KEY ("TRANSFERRED_FROM_ID")
	  REFERENCES "YODA"."PERSON" ("ID") ENABLE;
