CREATE TABLE "YODA"."USER_DATA" SHARING=METADATA 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(1), 
	"DOB" DATE
   ) ;
