CREATE TABLE "YODA"."ZIPCODE" SHARING=METADATA 
   (	"ZIP" VARCHAR2(5) CONSTRAINT "ZIP_ZIP_NNULL" NOT NULL ENABLE, 
	"CITY" VARCHAR2(25), 
	"STATE" VARCHAR2(2), 
	"CREATED_BY" VARCHAR2(30) CONSTRAINT "ZIP_CREATED_BY_NNULL" NOT NULL ENABLE, 
	"CREATED_DATE" DATE CONSTRAINT "ZIP_CREATED_DATE_NNULL" NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) CONSTRAINT "ZIP_MODIFIED_BY_NNULL" NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE CONSTRAINT "ZIP_MODIFIED_DATE_NNULL" NOT NULL ENABLE
   ) ;
ALTER TABLE "YODA"."ZIPCODE" ADD CONSTRAINT "ZIP_PK" PRIMARY KEY ("ZIP")
  USING INDEX  ENABLE;
