CREATE OR REPLACE FORCE EDITIONABLE VIEW "YODA"."FULL_TEXT_SEARCH_VIEW" ("ID", "ST_ID", "CL_TRN_DATA", "AMOUNT", "CURRENCY", "IP_ADDRESS", "SEARCH_DATA", "CREATION_DATE", "MODIFICATION_DATE", "LK_DT", "LOCKED_BY", "FORM_OF_PAYMENT", "PAYMENT_FOR_SERVICE", "DISCRIMINATOR", "R") AS 
  SELECT "ID","ST_ID","CL_TRN_DATA","AMOUNT","CURRENCY","IP_ADDRESS","SEARCH_DATA","CREATION_DATE","MODIFICATION_DATE","LK_DT","LOCKED_BY","FORM_OF_PAYMENT","PAYMENT_FOR_SERVICE","DISCRIMINATOR","R" FROM (
    SELECT ID,ST_ID,CL_TRN_DATA,AMOUNT,CURRENCY,IP_ADDRESS,SEARCH_DATA,CREATION_DATE,MODIFICATION_DATE,
        LK_DT,LOCKED_BY,FORM_OF_PAYMENT,PAYMENT_FOR_SERVICE,DISCRIMINATOR,
        row_number() over (order by SCORE(1) desc) r FROM FULL_TEXT_SEARCH_TBL
    WHERE DISCRIMINATOR = 'PO'
        AND creation_date >= '10/09/21'
        AND creation_date <= '18/09/21'
        AND contains(search_data,'ET5B5H',1)>0
)
WHERE r BETWEEN  0 AND 200;
