CREATE OR REPLACE FORCE EDITIONABLE VIEW "YODA"."VW_WITH_ANLYTIC_FNC_2" ("NUMERIC_GRADE", "RANK") AS 
  SELECT "NUMERIC_GRADE","RANK"
FROM (SELECT numeric_grade,
DENSE_RANK() OVER (ORDER BY numeric_grade)
AS rank FROM grade
WHERE student_id = 254 AND section_id = 87)
WHERE rank <= 3;
