CREATE TABLE "DEMO"."ADMCMPTAX" 
   (	"CODE" NUMBER(12,0), 
	"NAME" VARCHAR2(100), 
	"EXT" CHAR(1) DEFAULT 'N', 
	"ECODE" NUMBER(12,0), 
	"TIME" DATE DEFAULT sysdate, 
	"LAST_ACCESS_ECODE" NUMBER(12,0), 
	"LAST_ACCESS_TIME" DATE DEFAULT sysdate, 
	"TAXREVERSALDAYS" NUMBER(3,0), 
	"TAXREVERSALDAYS_PROC" NUMBER(3,0)
   ) ;
