CREATE TABLE "DEMO"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"DNAME" VARCHAR2(14), 
	"LOC" VARCHAR2(13)
   ) ;
  CREATE UNIQUE INDEX "DEMO"."PK_DEPT" ON "DEMO"."DEPT" ("DEPTNO") 
  ;
ALTER TABLE "DEMO"."DEPT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY ("DEPTNO")
  USING INDEX "DEMO"."PK_DEPT"  ENABLE;
