CREATE TABLE "DEMO"."DXRECEIVE" 
   (	"ID" NUMBER(12,0), 
	"WEBDXID" NUMBER(12,0), 
	"SENDDXID" NUMBER(12,0), 
	"DXRECEIVESESSIONID" NUMBER(12,0), 
	"DXPROCESSSESSIONID" NUMBER(12,0), 
	"SENDERCUID" VARCHAR2(14), 
	"STATUS" NUMBER(4,0), 
	"RECEIVEERROR" VARCHAR2(1000), 
	"CREATEDON" DATE, 
	"LASTMODIFIEDON" DATE, 
	"CP" VARCHAR2(15), 
	"SIGNATURE" RAW(2000), 
	"DXEVENTS" VARCHAR2(4000)
   ) ;
