CREATE TABLE "DEMO"."EMP" 
   (	"EMPNO" NUMBER(4,0), 
	"ENAME" VARCHAR2(10), 
	"JOB" VARCHAR2(9), 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER(2,0), 
	"DEPT_NAME" VARCHAR2(200), 
	"EMAIL" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "DEMO"."PK_EMP" ON "DEMO"."EMP" ("EMPNO") 
  ;
ALTER TABLE "DEMO"."EMP" ADD CONSTRAINT "PK_EMP" PRIMARY KEY ("EMPNO")
  USING INDEX "DEMO"."PK_EMP"  ENABLE;
ALTER TABLE "DEMO"."EMP" ADD CONSTRAINT "FK_DEPTNO" FOREIGN KEY ("DEPTNO")
	  REFERENCES "DEMO"."DEPT" ("DEPTNO") ENABLE;
