CREATE TABLE "DEMO"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER(5,0), 
	"LAST_NAME" VARCHAR2(50), 
	"EMAIL" VARCHAR2(100), 
	"HIRE_DATE" DATE, 
	"JOB_ID" VARCHAR2(10)
   ) ;
ALTER TABLE "DEMO"."EMPLOYEES" ADD PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX  ENABLE;
