CREATE TABLE "DEMO"."MD_APPLICATIONFILES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"APPLICATIONS_ID_FK" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"URI" VARCHAR2(4000) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"STATE" VARCHAR2(100) NOT NULL ENABLE, 
	"LANGUAGE" VARCHAR2(100), 
	"LOC" NUMBER, 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(4000), 
	"UPDATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(4000)
   ) ;
ALTER TABLE "DEMO"."MD_APPLICATIONFILES" ADD CONSTRAINT "MD_APPLICATIONFILES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
