CREATE TABLE "DEMO"."MD_COLUMNS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TABLE_ID_FK" NUMBER NOT NULL ENABLE, 
	"COLUMN_NAME" VARCHAR2(4000) NOT NULL ENABLE, 
	"COLUMN_ORDER" NUMBER NOT NULL ENABLE, 
	"COLUMN_TYPE" VARCHAR2(4000), 
	"PRECISION" NUMBER, 
	"SCALE" NUMBER, 
	"NULLABLE" CHAR(1) NOT NULL ENABLE, 
	"DEFAULT_VALUE" VARCHAR2(4000), 
	"NATIVE_SQL" CLOB, 
	"NATIVE_KEY" VARCHAR2(4000), 
	"DATATYPE_TRANSFORMED_FLAG" CHAR(1), 
	"COMMENTS" VARCHAR2(4000), 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE
   ) ;
ALTER TABLE "DEMO"."MD_COLUMNS" ADD CONSTRAINT "MD_COLUMNS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "DEMO"."MD_COLUMNS" ADD CONSTRAINT "MD_COLUMNS_NULLABLE_Y_N" CHECK ((UPPER(NULLABLE) IN ('Y','N'))) ENABLE;
