CREATE TABLE "DEMO"."MD_GROUP_MEMBERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"GROUP_ID_FK" NUMBER NOT NULL ENABLE, 
	"USER_ID_FK" NUMBER, 
	"GROUP_MEMBER_ID_FK" NUMBER, 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255)
   ) ;
ALTER TABLE "DEMO"."MD_GROUP_MEMBERS" ADD CONSTRAINT "MD_GROUP_MEMBERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
