CREATE TABLE "DEMO"."MD_MIGR_PARAMETER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CONNECTION_ID_FK" NUMBER NOT NULL ENABLE, 
	"OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"OBJECT_TYPE" VARCHAR2(4000) NOT NULL ENABLE, 
	"PARAM_EXISTING" NUMBER NOT NULL ENABLE, 
	"PARAM_ORDER" NUMBER NOT NULL ENABLE, 
	"PARAM_NAME" VARCHAR2(4000) NOT NULL ENABLE, 
	"PARAM_TYPE" VARCHAR2(4000) NOT NULL ENABLE, 
	"PARAM_DATA_TYPE" VARCHAR2(4000) NOT NULL ENABLE, 
	"PERCISION" NUMBER, 
	"SCALE" NUMBER, 
	"NULLABLE" CHAR(1) NOT NULL ENABLE, 
	"DEFAULT_VALUE" VARCHAR2(4000), 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255), 
	"LAST_UPDATED_ON" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255)
   ) ;
ALTER TABLE "DEMO"."MD_MIGR_PARAMETER" ADD CONSTRAINT "MIGR_PARAMETER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
