CREATE TABLE "DEMO"."MD_SEQUENCES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SCHEMA_ID_FK" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(4000) NOT NULL ENABLE, 
	"SEQ_START" NUMBER NOT NULL ENABLE, 
	"INCR" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"NATIVE_SQL" CLOB, 
	"NATIVE_KEY" VARCHAR2(4000), 
	"COMMENTS" VARCHAR2(4000), 
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255) DEFAULT '0' NOT NULL ENABLE, 
	"LAST_UPDATED_ON" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255)
   ) ;
ALTER TABLE "DEMO"."MD_SEQUENCES" ADD CONSTRAINT "MD_SEQUENCES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
