CREATE TABLE "DEMO"."MEDICAL_BILLS" 
   (	"BILL_ID" NUMBER(10,0), 
	"BILL_NUMBER" VARCHAR2(20), 
	"PARTY_NAME" VARCHAR2(50), 
	"BILL_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_DATE" DATE
   ) ;
ALTER TABLE "DEMO"."MEDICAL_BILLS" ADD PRIMARY KEY ("BILL_ID")
  USING INDEX  ENABLE;
