CREATE TABLE "DEMO"."MEMBER_STAGING" 
   (	"MEMBER_ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"RANK" VARCHAR2(20)
   ) ;
  CREATE UNIQUE INDEX "DEMO"."MEMBER_STAGING_PK" ON "DEMO"."MEMBER_STAGING" ("MEMBER_ID") 
  ;
ALTER TABLE "DEMO"."MEMBER_STAGING" ADD CONSTRAINT "MEMBER_STAGING_PK" PRIMARY KEY ("MEMBER_ID")
  USING INDEX "DEMO"."MEMBER_STAGING_PK"  ENABLE;
