CREATE TABLE "DEMO"."MEMBERS" 
   (	"MEMBER_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"RANK" VARCHAR2(20)
   ) ;
ALTER TABLE "DEMO"."MEMBERS" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX  ENABLE;
