CREATE TABLE "DEMO"."ORCLONE_SOURCE_CODE" 
   (	"OWNER" VARCHAR2(128 CHAR), 
	"NAME" VARCHAR2(128 CHAR), 
	"TYPE" VARCHAR2(12 CHAR), 
	"LINE" NUMBER, 
	"TEXT" VARCHAR2(4000 CHAR), 
	"ORIGIN_CON_ID" NUMBER
   ) ;
