CREATE TABLE "DEMO"."PSITE_GROUP" 
   (	"CODE" NUMBER(12,0), 
	"NAME" VARCHAR2(100), 
	"PARENTCODE" NUMBER(12,0), 
	"DISPLAY_ORDER" NUMBER(12,0), 
	"INDENT_LEVEL" NUMBER(12,0), 
	"CREATEDON" DATE, 
	"CREATEDBY" NUMBER(12,0), 
	"LASTMODIFIEDON" DATE, 
	"LASTMODIFIEDBY" NUMBER(12,0), 
	"DATAVERSION" NUMBER(12,0)
   ) ;
