CREATE TABLE "DEMO"."SALES_DATA" 
   (	"ORDER_ID" NUMBER, 
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
	"ORDER_DATE" DATE NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"AMOUNT" NUMBER(10,2) NOT NULL ENABLE
   ) 
  PARTITION BY RANGE ("ORDER_DATE") 
 (PARTITION "P2023_Q1"  VALUES LESS THAN (TO_DATE(' 2024-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , 
 PARTITION "P2023_Q2"  VALUES LESS THAN (TO_DATE(' 2024-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , 
 PARTITION "P2023_Q3"  VALUES LESS THAN (TO_DATE(' 2024-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) , 
 PARTITION "P2023_Q4"  VALUES LESS THAN (MAXVALUE) ) ;
ALTER TABLE "DEMO"."SALES_DATA" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE;
