CREATE TABLE "DEMO"."SALES_INTERVAL" 
   (	"ID" NUMBER, 
	"SALE_DATE" DATE, 
	"AMOUNT" NUMBER
   ) 
  PARTITION BY RANGE ("SALE_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "P_START"  VALUES LESS THAN (TO_DATE(' 2025-09-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
