CREATE TABLE "DEMO"."SURESHTESTEMP" 
   (	"EMP_ID" RAW(32) DEFAULT sys_guid() NOT NULL ENABLE, 
	"EMP_NAME" VARCHAR2(20), 
	"UID" VARCHAR2(20), 
	"JOIN" VARCHAR2(20)
   ) ;
ALTER TABLE "DEMO"."SURESHTESTEMP" ADD PRIMARY KEY ("EMP_ID")
  USING INDEX  ENABLE;
