CREATE OR REPLACE EDITIONABLE PROCEDURE "DEMO"."EMP_SAL_RAISE" (P_EMP_ID IN NUMBER, SAL_RAISE IN NUMBER,V_EMP_CURRENT_SAL out NUMBER)
    AS
-- PGV moved types start

-- PGV moved types end

   

    BEGIN

        DBMS_OUTPUT.ENABLE ;
     SELECT sal INTO V_EMP_CURRENT_SAL FROM demo.emp WHERE EMPNO=P_EMP_ID ;


        DBMS_OUTPUT.PUT_LINE((V_EMP_CURRENT_SAL+SAL_RAISE));
    EXCEPTION WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
ROLLBACK;
COMMIT;
END; 

/
