CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DEMO"."SALES_STAFF" ("EMPNO", "ENAME", "DEPTNO") AS 
  SELECT empno, ename, deptno
     FROM emp
     WHERE deptno = 30
     WITH CHECK OPTION  CONSTRAINT "SALES_STAFF_CNST";
